file(MAKE_DIRECTORY "${TEST_DIR}")
file(WRITE "${TEST_DIR}/good.asm" "LDI R1, #-1\nRET\n")
file(WRITE "${TEST_DIR}/good.bin" "stale output")
execute_process(COMMAND "${ASM}" "${TEST_DIR}/good.asm" -o "${TEST_DIR}/good.bin" RESULT_VARIABLE rc ERROR_VARIABLE err)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "assembler failed: ${err}")
endif()
file(READ "${TEST_DIR}/good.bin" actual HEX)
if(NOT actual STREQUAL "ffff0f210000d0a0")
  message(FATAL_ERROR "wrong output bytes: ${actual}")
endif()
file(WRITE "${TEST_DIR}/bad.asm" "NOP\nADDI R1, R2, #999999\n")
execute_process(COMMAND "${ASM}" "${TEST_DIR}/bad.asm" -o "${TEST_DIR}/bad.bin" RESULT_VARIABLE rc ERROR_VARIABLE err)
if(rc EQUAL 0 OR NOT err MATCHES "bad.asm:2:14: error:")
  message(FATAL_ERROR "invalid input diagnostic missing: ${err}")
endif()
if(UNIX AND EXISTS "/dev/full")
  execute_process(COMMAND "${ASM}" "${TEST_DIR}/good.asm" -o /dev/full RESULT_VARIABLE rc ERROR_VARIABLE err)
  if(rc EQUAL 0 OR NOT err MATCHES "failed writing output")
    message(FATAL_ERROR "output flush failure was not reported: ${err}")
  endif()
endif()
